name: Contribute List

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Contribute List
      uses: niteshseram/contribute-list@v1.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        contribute_list: README.md
        contributors_per_row: 4
        readme_path: README.md
        start_title: '<!-- START CONTRIBUTORS LIST -->'
        end_title: '<!-- END CONTRIBUTORS LIST -->'
