name: Update Contributors List

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Contributors List
        uses: docker://jakejarvis/contributors-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          README_PATH: 'README.md'
          MAX_LINES: 7
