name: Update Contributors List

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Contributors List
        uses: actions/github-script@v6
        with:
          script: |
            const contributors = await github.paginate(
              github.repos.listContributors.endpoint.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              })
            );

            const contributorList = contributors.map(
              contributor => `![${contributor.login}](${contributor.avatar_url}&s=64) | **[@${contributor.login}](${contributor.html_url})**`
            ).join('\n');

            const readmeContent = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md'
            });

            const readmeBuffer = Buffer.from(readmeContent.data.content, 'base64');
            let readmeText = readmeBuffer.toString('utf-8');

            const startMarker = '<!-- markdown-contributors -->';
            const endMarker = '<!-- /markdown-contributors -->';

            const startIndex = readmeText.indexOf(startMarker) + startMarker.length;
            const endIndex = readmeText.indexOf(endMarker);

            const newReadmeText = `${readmeText.substring(0, startIndex)}\n${contributorList}\n${readmeText.substring(endIndex)}`;

            const newReadmeBuffer = Buffer.from(newReadmeText, 'utf-8');

            await github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'README.md',
              message: 'Update contributors list',
              content: newReadmeBuffer.toString('base64'),
              sha: readmeContent.data.sha
            });
